
services:
  back-api:
    container_name: back-api
    image: back/back:1.0-SNAPSHOT
    ports:
      - 8088:8088
    networks:
      - spring-demo
    secrets:
      - mongo-db-uri

  front-ui:
    container_name: front-ui
    image: front/front-ui:1.0-SNAPSHOT
    ports:
      - 8000:80
    networks:
      - spring-demo
    depends_on:
      - back-api
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local


secrets:
  mongo-db-uri:
    external: true
